export const ADD_PROMOTION = 'ADD_PROMOTION';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';

export const DATA_LOADER_LOADING = 'DATA_LOADER_LOADING';
export const DATA_LOADER_COMPLETED = 'DATA_LOADER_COMPLETE';
export const DATA_LOADER_ERROR = 'DATA_LOADER_ERROR';
